org: nextjs-serverless-template
app: nextjs-serverless-template-node16
stage: dev
component: layer
name: nextjs-serverless-template-node16-layer
inputs:
  name: nextjs-serverless-template-node16-layer
  region: ap-guangzhou
  src:
    src: ../node_modules
    targetDir: /node_modules
  runtimes:
    - Nodejs16.13
