org: nextjs-serverless-template
name: nextjs-serverless-template-node16
app: nextjs-serverless-template-node16
stage: dev
component: http
inputs:
  src:
    dist: ./
    hook: npm run build
    exclude:
      - .env
  faas:
    runtime: Nodejs16.13
    framework: nextjs
    name: "${name}"
    eip: false
    timeout: 10
    memorySize: 512
    tags: []
    environments: []
    layers:
      - name: "${output:${stage}:${app}:${app}-layer.name}"
        version: "${output:${stage}:${app}:${app}-layer.version}"
  apigw:
    protocols:
      - http
      - https
    timeout: 60
    environment: release
    customDomains: []
  region: ap-guangzhou
  isAutoCiDeploy: false
